# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import vtk
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
import global_variables as gvars
import data_support_code as data_sc
import graphics_support_code as graphics_sc
import interactivity_support_code as interact_sc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rotX = QtWidgets.QPushButton(self.centralwidget)
        self.rotX.setGeometry(QtCore.QRect(20, 580, 71, 31))
        self.rotX.setObjectName("rotX")
        self.transX = QtWidgets.QSlider(self.centralwidget)
        self.transX.setGeometry(QtCore.QRect(20, 620, 160, 22))
        self.transX.setWhatsThis("")
        self.transX.setMinimum(-400)
        self.transX.setMaximum(400)
        self.transX.setOrientation(QtCore.Qt.Horizontal)
        self.transX.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.transX.setObjectName("transX")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 650, 71, 16))
        self.label.setObjectName("label")

        self.vl = QtWidgets.QVBoxLayout()
        self.vl.setGeometry(QtCore.QRect(10,10,1000,550))
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("vtkthing")
        self.frame.setLayout(self.vl)
        self.frame.setFixedWidth(990)
        self.frame.setFixedHeight(550)
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
        self.vl.addWidget(self.vtkWidget)
        self.ren = gvars.renderer_for_qt
        self.ren.SetBackground(gvars.colors.GetColor3d('SlateGray'))
        self.ren.ResetCamera()
        self.vtkWidget.GetRenderWindow().AddRenderer(self.ren)
        self.iren = self.vtkWidget.GetRenderWindow().GetInteractor()
        gvars.iren_qt = self.iren
        graphics_sc.addActors(self.ren)
        self.iren.Initialize()

        self.transY = QtWidgets.QSlider(self.centralwidget)
        self.transY.setGeometry(QtCore.QRect(200, 620, 160, 22))
        self.transY.setWhatsThis("")
        self.transY.setMinimum(-400)
        self.transY.setMaximum(400)
        self.transY.setOrientation(QtCore.Qt.Horizontal)
        self.transY.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.transY.setObjectName("transY")
        self.transZ = QtWidgets.QSlider(self.centralwidget)
        self.transZ.setGeometry(QtCore.QRect(380, 620, 160, 22))
        self.transZ.setWhatsThis("")
        self.transZ.setMinimum(-150)
        self.transZ.setMaximum(150)
        self.transZ.setOrientation(QtCore.Qt.Horizontal)
        self.transZ.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.transZ.setObjectName("transZ")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 650, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 650, 71, 16))
        self.label_3.setObjectName("label_3")
        self.rotZ = QtWidgets.QPushButton(self.centralwidget)
        self.rotZ.setGeometry(QtCore.QRect(380, 580, 71, 31))
        self.rotZ.setObjectName("rotZ")
        self.rotY = QtWidgets.QPushButton(self.centralwidget)
        self.rotY.setGeometry(QtCore.QRect(200, 580, 71, 31))
        self.rotY.setObjectName("rotY")
        self.file_select = QtWidgets.QPushButton(self.centralwidget)
        self.file_select.setGeometry(QtCore.QRect(750, 580, 91, 31))
        self.file_select.setObjectName("file_select")
        self.get_export_2 = QtWidgets.QPushButton(self.centralwidget)
        self.get_export_2.setGeometry(QtCore.QRect(750, 620, 91, 31))
        self.get_export_2.setObjectName("get_export_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(640, 580, 42, 22))
        self.spinBox.setMaximum(600)
        self.spinBox.setProperty("value", 60)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 580, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.reset_sliders = QtWidgets.QPushButton(self.centralwidget)
        self.reset_sliders.setGeometry(QtCore.QRect(570, 620, 91, 31))
        self.reset_sliders.setObjectName("reset_sliders")

        self.get_export_2.clicked.connect(interact_sc.get_export_data)
        self.file_select.clicked.connect(interact_sc.select_load_file)
        self.rotX.clicked.connect(interact_sc.rotX)
        self.rotY.clicked.connect(interact_sc.rotY)
        self.rotZ.clicked.connect(interact_sc.rotZ)
        self.reset_sliders.clicked.connect(lambda: interact_sc.reset_sliders(self.transX, self.transY, self.transZ))
        self.transX.sliderReleased.connect(lambda: interact_sc.translateX(self.transX.value()))
        self.transY.sliderReleased.connect(lambda: interact_sc.translateY(self.transY.value()))
        self.transZ.sliderReleased.connect(lambda: interact_sc.translateZ(self.transZ.value()))
        self.spinBox.valueChanged.connect(lambda: interact_sc.heating_time_updated(self.spinBox.value()))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Computer GUI - Formagine"))
        self.rotX.setText(_translate("MainWindow", "Rotate X"))
        self.label.setText(_translate("MainWindow", "Translate X"))
        self.label_2.setText(_translate("MainWindow", "Translate Y"))
        self.label_3.setText(_translate("MainWindow", "Translate Z"))
        self.rotZ.setText(_translate("MainWindow", "Rotate Z"))
        self.rotY.setText(_translate("MainWindow", "Rotate Y"))
        self.file_select.setText(_translate("MainWindow", "File Select"))
        self.get_export_2.setText(_translate("MainWindow", "Data Export"))
        self.label_4.setText(_translate("MainWindow", "Heating time:"))
        self.reset_sliders.setText(_translate("MainWindow", "Reset Sliders"))
