# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import vtk
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
import global_variables as gvars
import data_support_code as data_sc
import graphics_support_code as graphics_sc
import interactivity_support_code as interact_sc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rotX = QtWidgets.QPushButton(self.centralwidget)
        self.rotX.setGeometry(QtCore.QRect(100, 600, 71, 31))
        self.rotX.setObjectName("rotX")
        self.transX = QtWidgets.QSlider(self.centralwidget)
        self.transX.setGeometry(QtCore.QRect(200, 600, 160, 22))
        self.transX.setWhatsThis("")
        self.transX.setMinimum(-400)
        self.transX.setMaximum(400)
        self.transX.setOrientation(QtCore.Qt.Horizontal)
        self.transX.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.transX.setObjectName("transX")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 630, 71, 16))
        self.label.setObjectName("label")
        
        # self.fuck = QtWidgets.QFrame(self.centralwidget)
        # self.fuck.setGeometry(QtCore.QRect(370, 180, 120, 80))
        # self.fuck.setObjectName("fuck")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(370, 180, 500, 300))
        self.frame.setObjectName("vtkthing")
        self.vl = QtWidgets.QVBoxLayout()
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
        self.vl.addWidget(self.vtkWidget)
        self.ren = gvars.renderer_for_qt
        self.ren.SetBackground(gvars.colors.GetColor3d('SlateGray'))
        self.ren.ResetCamera()
        self.vtkWidget.GetRenderWindow().AddRenderer(self.ren)
        self.iren = self.vtkWidget.GetRenderWindow().GetInteractor()
        gvars.iren_qt = self.iren
        graphics_sc.addActors(self.ren)
        self.iren.Initialize()

        # Adding y-translation slider for testing
        self.transY = QtWidgets.QSlider(self.centralwidget)
        self.transY.setGeometry(QtCore.QRect(400, 600, 160, 22))
        self.transY.setWhatsThis("")
        self.transY.setMinimum(-400)
        self.transY.setMaximum(400)
        self.transY.setOrientation(QtCore.Qt.Horizontal)
        self.transY.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.transY.setObjectName("transY")


        self.rotX.clicked.connect(interact_sc.testFunc)
        # print("val: " + str(self.transX.value()))
        self.transX.sliderReleased.connect(lambda: interact_sc.translateX(self.transX.value()))
        self.transY.sliderReleased.connect(lambda: interact_sc.translateY(self.transY.value()))


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Computer GUI - Formagine"))
        self.rotX.setText(_translate("MainWindow", "Rotate X"))
        self.label.setText(_translate("MainWindow", "Translate X"))
